Create TOS.html
01000011-00110111/School-Chat pull request #92
Opened 2023-07-30 05:11 UTC by CastyiGlitchxz

I create a html file for the terms of service and rules.

2023-07-30 05:13 UTC, 01000011-00110111 requested changes
Add some styling and add some example text for us too se how everything works

2023-08-29 02:44 UTC, cserver45 requested changes
I like it, but we should add in a few things

2023-08-29 02:44 UTC, cserver45 commented on TOS.html
> +  <meta charset="utf-8">
Need to add the other <meta> tags we have in index.html

2023-08-29 02:44 UTC, cserver45 commented on TOS.html
> +  <link href="style.css" rel="stylesheet" type="text/css" />
Should we just create a new style.css file just for this? or just try to use as much as we can from the main style.css file?

2023-08-29 02:44 UTC, cserver45 commented on TOS.html
> +        <button class="ToSBtn">Copyright Policy</button>
change this to Licence info (because this is licenced under the AGPL)

2023-08-30 13:28 UTC, CastyiGlitchxz reviewed
Nice Ideas.

2023-08-31 14:20 UTC, closed without merging